### ISSUE TITLE
Looking for 6.5.1 release

### ISSUE THREAD

**Issue by qakart** [maliceio/malice-kibana-plugin#8]
As i am using 6.5.1 is there any way to get this specific version 

thanks in advance
karthik

**Comment by blacktop** [comment]
So it takes a while for me to make releases because I use: https://github.com/blacktop/kibana-plugin-builder, mostly because I don't want to have a bunch of different versions of nodeJS installed via NVM and trying to keep java off my dev machine 😆 

Basically you build a release of the **kibana-plugin-builder** then change the version in the package.json in this project and `make plugin` and THEN you can install the plugin from the ZIP in kibana.

**Comment by blacktop** [comment]
```bash
$ git clone https://github.com/blacktop/kibana-plugin-builder.git
$ cd kibana-plugin-builder
$ VERSION=6.5.1 make build
```

**Comment by blacktop** [comment]
```bash
git clone https://github.com/maliceio/malice-kibana-plugin.git
cd malice-kibana-plugin
# update version in package.json
make plugin
```

**Comment by blacktop** [comment]
Closing.  Feel free to open if you have anymore questions.
